# Sources: https://medium.com/@saygiligozde/using-docker-compose-with-spring-boot-and-postgresql-235031106f9f
#         https://spring.io/blog/2023/06/21/docker-compose-support-in-spring-boot-3-1

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=invease_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - backend

  backend:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/invease_db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge